import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <style>{`
          * {
            font-family: 'DM Sans', 'Inter', 'Roboto', sans-serif !important;
          }
          
          /* Headings keep Playfair Display */
          h1, h2, h3, .playfair {
            font-family: 'Playfair Display', 'DM Sans', serif !important;
          }
        `}</style>
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;0,900;1,700&family=DM+Sans:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>{children}</body>
    </html>
  )
}
